/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.HealthDeptWork;

import business.Network.Network;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author ngmodani
 */
public class HOWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Network n;

    /**
     * Creates new form AdminWorkAreaPanel
     */
    public HOWorkAreaJPanel(JPanel userProcessContainer, Network n, UserAccount ua) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.n = n;
        enterpriseLabel.setText("Welcome " + ua.getPerson().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        btnAvgVitals = new javax.swing.JButton();
        btnHealthStats = new javax.swing.JButton();
        btnRequestEPA = new javax.swing.JButton();
        btnReportMayor = new javax.swing.JButton();

        setBackground(new java.awt.Color(52, 169, 66));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("New Peninim MT", 1, 18)); // NOI18N
        jLabel1.setText("My Work Area -Health Officer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("New Peninim MT", 1, 14)); // NOI18N
        enterpriseLabel.setText("Welcome ");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 290, 30));

        btnAvgVitals.setBackground(new java.awt.Color(153, 153, 153));
        btnAvgVitals.setFont(new java.awt.Font("Chalkduster", 1, 14)); // NOI18N
        btnAvgVitals.setText("Avg. Vitals Statistics");
        btnAvgVitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvgVitalsActionPerformed(evt);
            }
        });
        add(btnAvgVitals, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        btnHealthStats.setBackground(new java.awt.Color(153, 153, 153));
        btnHealthStats.setFont(new java.awt.Font("Chalkduster", 1, 14)); // NOI18N
        btnHealthStats.setText("Health Statistics");
        btnHealthStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHealthStatsActionPerformed(evt);
            }
        });
        add(btnHealthStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        btnRequestEPA.setBackground(new java.awt.Color(153, 153, 153));
        btnRequestEPA.setFont(new java.awt.Font("Chalkduster", 1, 14)); // NOI18N
        btnRequestEPA.setText("Request EPA Assistance");
        btnRequestEPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestEPAActionPerformed(evt);
            }
        });
        add(btnRequestEPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        btnReportMayor.setBackground(new java.awt.Color(153, 153, 153));
        btnReportMayor.setFont(new java.awt.Font("Chalkduster", 1, 14)); // NOI18N
        btnReportMayor.setText("Reporting to Mayor");
        btnReportMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportMayorActionPerformed(evt);
            }
        });
        add(btnReportMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvgVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvgVitalsActionPerformed

        AvgVitalsJPanel avjp = new AvgVitalsJPanel(userProcessContainer, n);
        userProcessContainer.add("AvgVitalsJPanel", avjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAvgVitalsActionPerformed

    private void btnHealthStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHealthStatsActionPerformed
        // TODO add your handling code here:
        MedicalRecordStatsJPanel mrsjp = new MedicalRecordStatsJPanel(userProcessContainer, n);
        userProcessContainer.add("MedicalRecordStatsJPanel", mrsjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnHealthStatsActionPerformed

    private void btnRequestEPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestEPAActionPerformed
        // TODO add your handling code here:

        RequestsToEPAJPanel rtepajp = new RequestsToEPAJPanel(userProcessContainer, n, userAccount);
        userProcessContainer.add("RequestsToEPAJPanel", rtepajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRequestEPAActionPerformed

    private void btnReportMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportMayorActionPerformed
        // TODO add your handling code here:
        SendUpdateToMayorJPanel stmjp = new SendUpdateToMayorJPanel(userProcessContainer, n);
        userProcessContainer.add("SendUpdateToMayorJPanel", stmjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnReportMayorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvgVitals;
    private javax.swing.JButton btnHealthStats;
    private javax.swing.JButton btnReportMayor;
    private javax.swing.JButton btnRequestEPA;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
