/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.EPAWork;

import business.Enterprise.CityCouncilEnterprise;
import ui.HealthDeptWork.*;
import ui.AdminResidentRole.*;
import business.Enterprise.Enterprise;
import business.Network.Network;
import business.Organization.EnvironmentDeptOrganization;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author ngmodani
 */
public class EPAWorkAreaPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Network n;

    /**
     * Creates new form AdminWorkAreaPanel
     */
    public EPAWorkAreaPanel(JPanel userProcessContainer, Network n, UserAccount ua) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.n = n;
        this.userAccount = ua;
        enterpriseLabel.setText("Welcome " + ua.getPerson().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        btnAirQuality = new javax.swing.JButton();
        btnViewRequests = new javax.swing.JButton();
        btnReportMayor = new javax.swing.JButton();

        setBackground(new java.awt.Color(133, 210, 226));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("New Peninim MT", 1, 18)); // NOI18N
        jLabel1.setText("My Work Area -EPA Officer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("New Peninim MT", 1, 14)); // NOI18N
        enterpriseLabel.setText("Welcome ");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 230, 30));

        btnAirQuality.setBackground(new java.awt.Color(153, 153, 153));
        btnAirQuality.setFont(new java.awt.Font("Chalkduster", 1, 14)); // NOI18N
        btnAirQuality.setText("Air Quality Statistics");
        btnAirQuality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirQualityActionPerformed(evt);
            }
        });
        add(btnAirQuality, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        btnViewRequests.setBackground(new java.awt.Color(153, 153, 153));
        btnViewRequests.setFont(new java.awt.Font("Chalkduster", 1, 14)); // NOI18N
        btnViewRequests.setText("View Requests from Health Dept.");
        btnViewRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRequestsActionPerformed(evt);
            }
        });
        add(btnViewRequests, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        btnReportMayor.setBackground(new java.awt.Color(153, 153, 153));
        btnReportMayor.setFont(new java.awt.Font("Chalkduster", 1, 14)); // NOI18N
        btnReportMayor.setText("Reporting to Mayor");
        btnReportMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportMayorActionPerformed(evt);
            }
        });
        add(btnReportMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAirQualityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirQualityActionPerformed

        AirQualityStatisticsJPanel aqsjp = new AirQualityStatisticsJPanel(userProcessContainer, n);
        userProcessContainer.add("AirQualityStatisticsJPanel", aqsjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAirQualityActionPerformed

    private void btnViewRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRequestsActionPerformed
        // TODO add your handling code here:
        for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof CityCouncilEnterprise) {
                for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                    if (o instanceof EnvironmentDeptOrganization) {
                        ViewRequestsJPanel vrjp = new ViewRequestsJPanel(userProcessContainer, (EnvironmentDeptOrganization) o,userAccount);
                        userProcessContainer.add("ViewRequestsJPanel", vrjp);
                        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                        layout.next(userProcessContainer);
                    }
                }
            }
        }

    }//GEN-LAST:event_btnViewRequestsActionPerformed

    private void btnReportMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportMayorActionPerformed
        // TODO add your handling code here:
        SendUpdateToMayorJPanel sutmjp = new SendUpdateToMayorJPanel(userProcessContainer, n);
        userProcessContainer.add("SendUpdateToMayorJPanel", sutmjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnReportMayorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAirQuality;
    private javax.swing.JButton btnReportMayor;
    private javax.swing.JButton btnViewRequests;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
