/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.ResidentWork;

import business.Enterprise.Enterprise;
import business.Network.Network;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ngmodani
 */
public class ResidentWorkAreaPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount ua;
    private Network net;
    private Enterprise e;

    /**
     * Creates new form AdminWorkAreaPanel
     */
    public ResidentWorkAreaPanel(JPanel userProcessContainer, Enterprise e, UserAccount ua, Network net) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ua = ua;
        this.net = net;
        this.e = e;
        valueLabel.setText("Welcome "+ua.getResident().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageHealth = new javax.swing.JButton();
        manageVitalsJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        manageProfileJButton = new javax.swing.JButton();
        btnRequestDocAdvice = new javax.swing.JButton();

        setBackground(new java.awt.Color(245, 153, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("New Peninim MT", 1, 18)); // NOI18N
        jLabel1.setText("My Work Area -Resident Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        btnManageHealth.setBackground(new java.awt.Color(153, 153, 153));
        btnManageHealth.setFont(new java.awt.Font("Chalkduster", 1, 14)); // NOI18N
        btnManageHealth.setText("Manage Health Record");
        btnManageHealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageHealthActionPerformed(evt);
            }
        });
        add(btnManageHealth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 220, -1));

        manageVitalsJButton.setBackground(new java.awt.Color(153, 153, 153));
        manageVitalsJButton.setFont(new java.awt.Font("Chalkduster", 1, 14)); // NOI18N
        manageVitalsJButton.setText("Manage Vital Signs");
        manageVitalsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageVitalsJButtonActionPerformed(evt);
            }
        });
        add(manageVitalsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 190, -1));

        valueLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 130, -1));

        manageProfileJButton.setBackground(new java.awt.Color(153, 153, 153));
        manageProfileJButton.setFont(new java.awt.Font("Chalkduster", 1, 14)); // NOI18N
        manageProfileJButton.setText("Manage Profile");
        manageProfileJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProfileJButtonActionPerformed(evt);
            }
        });
        add(manageProfileJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        btnRequestDocAdvice.setBackground(new java.awt.Color(153, 153, 153));
        btnRequestDocAdvice.setFont(new java.awt.Font("Chalkduster", 1, 14)); // NOI18N
        btnRequestDocAdvice.setText("Request Medical Help");
        btnRequestDocAdvice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestDocAdviceActionPerformed(evt);
            }
        });
        add(btnRequestDocAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void checkAge() {

    }

    private void btnManageHealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageHealthActionPerformed
        // TODO add your handling code here:
        if (ua.getResident().getDOB() == null) {
            JOptionPane.showMessageDialog(this, "Please update Profile!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        ManageHealthJPanel mhjp = new ManageHealthJPanel(userProcessContainer, ua);
        userProcessContainer.add("ManageHealthJPanel", mhjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageHealthActionPerformed

    private void manageVitalsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageVitalsJButtonActionPerformed
        if (ua.getResident().getDOB() == null) {
            JOptionPane.showMessageDialog(this, "Please update Profile!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        ManageVitalSignsJPanel mvsjp = new ManageVitalSignsJPanel(userProcessContainer, ua.getResident());
        userProcessContainer.add("ManageVitalSignsJPanel", mvsjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageVitalsJButtonActionPerformed

    private void manageProfileJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProfileJButtonActionPerformed

        UpdateProfileJPanel upjp = new UpdateProfileJPanel(userProcessContainer, ua.getResident());
        userProcessContainer.add("UpdateProfileJPanel", upjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageProfileJButtonActionPerformed

    private void btnRequestDocAdviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestDocAdviceActionPerformed
        // TODO add your handling code here:
        if (ua.getResident().getDOB() == null) {
            JOptionPane.showMessageDialog(this, "Please update Profile!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else if (ua.getResident().getVsHistory().getHistory().size() < 1) {
            JOptionPane.showMessageDialog(this, "No vital signs found. Please Enter your vital signs to Request Medical Help!", "Warning", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        ResidentDocRequestJPanel rdrjp = new ResidentDocRequestJPanel(userProcessContainer, ua, net);
        userProcessContainer.add("ResidentDocRequestJPanel", rdrjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnRequestDocAdviceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageHealth;
    private javax.swing.JButton btnRequestDocAdvice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageProfileJButton;
    private javax.swing.JButton manageVitalsJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
