/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AdminResidentRole;

import business.Enterprise.Enterprise;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.Random;
import javax.swing.JPanel;

/**
 *
 * @author ngmodani
 */
public class AdminWorkAreaPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Random random;

    /**
     * Creates new form AdminWorkAreaPanel
     */
    public AdminWorkAreaPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount ua) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        valueLabel.setText(enterprise.getName());
        random = new Random();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userJButton = new javax.swing.JButton();
        manageEmployeeJButton = new javax.swing.JButton();
        manageHouseJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        manageOrganizationJButton1 = new javax.swing.JButton();
        btnManageSensors = new javax.swing.JButton();
        btnGenerateSensorData = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("New Peninim MT", 1, 18)); // NOI18N
        jLabel1.setText("My Work Area -Aminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        userJButton.setBackground(new java.awt.Color(153, 153, 153));
        userJButton.setFont(new java.awt.Font("Chalkduster", 1, 14)); // NOI18N
        userJButton.setText("Manage User Accounts");
        userJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJButtonActionPerformed(evt);
            }
        });
        add(userJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 220, -1));

        manageEmployeeJButton.setBackground(new java.awt.Color(153, 153, 153));
        manageEmployeeJButton.setFont(new java.awt.Font("Chalkduster", 1, 14)); // NOI18N
        manageEmployeeJButton.setText("Manage Residents");
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });
        add(manageEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 170, -1));

        manageHouseJButton.setBackground(new java.awt.Color(153, 153, 153));
        manageHouseJButton.setFont(new java.awt.Font("Chalkduster", 1, 14)); // NOI18N
        manageHouseJButton.setText("Manage Houses");
        manageHouseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageHouseJButtonActionPerformed(evt);
            }
        });
        add(manageHouseJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        valueLabel.setFont(new java.awt.Font("New Peninim MT", 1, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, -1));

        manageOrganizationJButton1.setBackground(new java.awt.Color(153, 153, 153));
        manageOrganizationJButton1.setFont(new java.awt.Font("Chalkduster", 1, 14)); // NOI18N
        manageOrganizationJButton1.setText("Manage Communities");
        manageOrganizationJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButton1ActionPerformed(evt);
            }
        });
        add(manageOrganizationJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        btnManageSensors.setBackground(new java.awt.Color(153, 153, 153));
        btnManageSensors.setFont(new java.awt.Font("Chalkduster", 1, 14)); // NOI18N
        btnManageSensors.setText("Manage Community Sensors");
        btnManageSensors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSensorsActionPerformed(evt);
            }
        });
        add(btnManageSensors, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        btnGenerateSensorData.setBackground(new java.awt.Color(153, 153, 153));
        btnGenerateSensorData.setFont(new java.awt.Font("Chalkduster", 1, 14)); // NOI18N
        btnGenerateSensorData.setText("Generate Sensor Data");
        btnGenerateSensorData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateSensorDataActionPerformed(evt);
            }
        });
        add(btnGenerateSensorData, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void userJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJButtonActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userJButtonActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed

        ManagePersonJPanel manageEmployeeJPanel = new ManagePersonJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

    private void manageHouseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageHouseJButtonActionPerformed
        CreateHouseJPanel chjp = new CreateHouseJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("CreateHouseJPanel", chjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageHouseJButtonActionPerformed

    private void manageOrganizationJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButton1ActionPerformed

        ManageCommuityJPanel manageOrganizationJPanel = new ManageCommuityJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationJButton1ActionPerformed

    private void btnGenerateSensorDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateSensorDataActionPerformed
        // TODO add your handling code here:
        GenerateSensorDataJPanel gsdjp = new GenerateSensorDataJPanel(userProcessContainer, enterprise.getOrganizationDirectory(), random);
        userProcessContainer.add("GenerateSensorDataJPanel", gsdjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnGenerateSensorDataActionPerformed

    private void btnManageSensorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSensorsActionPerformed
        // TODO add your handling code here:
        ManageCommunitySensorsJPanel mcsjp = new ManageCommunitySensorsJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("ManageCommunitySensorsJPanel", mcsjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnManageSensorsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateSensorData;
    private javax.swing.JButton btnManageSensors;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JButton manageHouseJButton;
    private javax.swing.JButton manageOrganizationJButton1;
    private javax.swing.JButton userJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
